parallel run exception

diff --git a/cloudbuild/perf.yaml b/cloudbuild/perf.yaml
--- a/cloudbuild/perf.yaml
+++ b/cloudbuild/perf.yaml
@@ -94,20 +94,18 @@ steps:
           pip install -r requirements.txt
           python3 main.py 8192_objs_gcs_central1 --benchmark init-source-dataset
           python3 main.py medium_gcs_west1 --benchmark delete &
-          pid1=$$!
+          PID1=\$!
           python3 main.py 8192_objs_gcs_central1 --benchmark rename &
-          pid2=$$!
-
-          wait $$pid1
-          if [ $$? -ne 0 ]; then
-            echo "Delete benchmark failed"
-            exit 1
-          fi
-
-          wait $$pid2
-          if [ $$? -ne 0 ]; then
-            echo "Rename benchmark failed"
-            exit 1
+          PID2=\$!
+          wait \$PID1
+          STATUS1=\$?
+          wait \$PID2
+          STATUS2=\$?
+          if [ \$STATUS1 -ne 0 ] || [ \$STATUS2 -ne 0 ]; then
+            echo 'One or more parallel benchmarks failed!'
+            exit 1 
+          else
+            echo 'All parallel benchmarks completed successfully.'
           fi
         "
 
