comment

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -95,18 +95,18 @@ steps:
           python3 main.py 8192_objs_gcs_central1 --benchmark init-source-dataset
 
           # Run benchmarks in parallel
-          python3 main.py 8192_objs_gcs_central1 --benchmark delete &
-          PID1=$$!
-          python3 main.py 8192_objs_gcs_central1 --benchmark rename &
-          PID2=$$!
+          python3 main.py 8192_objs_gcs_central1 --benchmark delete #&
+          # PID1=$$!
+          # python3 main.py 8192_objs_gcs_central1 --benchmark rename &
+          # PID2=$$!
 
           # Wait for benchmarks to finish and check exit codes
-          if wait $$PID1 && wait $$PID2; then
-            echo "Benchmarks completed successfully"
-          else
-            echo "One or more benchmarks failed"
-            exit 1
-          fi
+          # if wait $$PID1 && wait $$PID2; then
+          #   echo "Benchmarks completed successfully"
+          # else
+          #   echo "One or more benchmarks failed"
+          #   exit 1
+          # fi
         "
 
         # Execute the script on the VM via SSH.
