Update pre-commit, add python versions (#508)
* Update pre-commit, add python versions

* Skip fuse test for some python versions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,49 +2,55 @@ name: CI
 
 on: [push, pull_request, workflow_dispatch]
 
+defaults:
+  run:
+    shell: bash -l -eo pipefail {0}
+
 jobs:
   test:
     name: Python ${{ matrix.python-version }}
     runs-on: ubuntu-latest
+    timeout-minutes: 10
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.7", "3.8", "3.9"]
+        python-version: ["3.7", "3.8", "3.9", "3.10"]
 
     steps:
       - name: Checkout source
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Setup Conda Environment
-        uses: conda-incubator/setup-miniconda@v2
+        uses: mamba-org/provision-with-micromamba@main
         with:
-          auto-update-conda: true
-          miniconda-version: latest
-          activate-environment: test
-          python-version: ${{ matrix.python-version }}
+          cache-downloads: true
+          environment-file: environment_gcsfs.yaml
+          environment-name: gcsfs_test
+          extra-specs: |
+            python=${{ matrix.python-version }}
 
-      - name: Install dependencies
-        shell: bash -l {0}
+      - name: Conda info
         run: |
-          conda install -c conda-forge pytest ujson requests decorator google-auth aiohttp google-auth-oauthlib google-cloud-core google-api-core google-api-python-client -y
-          pip install git+https://github.com/fsspec/filesystem_spec --no-deps
           conda list
           conda --version
 
-      - name: Install
-        shell: bash -l {0}
-        run: pip install .[crc]
+      - name: Install libfuse
+        run: (sudo apt-get install -y fuse || echo "Error installing fuse.")
 
-      - name: Run Tests
-        shell: bash -l {0}
+      - name: Run tests
         run: |
-            export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcsfs/tests/fake-secret.json
-            py.test -vv gcsfs
+          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcsfs/tests/fake-secret.json
+          pytest -vv \
+          --log-format="%(asctime)s %(levelname)s %(message)s" \
+          --log-date-format="%H:%M:%S" \
+          gcsfs/
 
   lint:
     name: lint
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - uses: actions/setup-python@v2
-    - uses: pre-commit/action@v2.0.0
+      - uses: actions/checkout@v3.1.0
+      - uses: actions/setup-python@v4
+        with:
+          python-version: "3.9"
+      - uses: pre-commit/action@v3.0.0
